/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inadex_gui;

import Controladores.ControladoresEquipos.ControladorRaimon;

import Inadex_gui.VistasEquipos.VistaRaimon;
import Modelos.Jugador;
import Servicios.Servicios;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;
/**
 *
 * @author zenca
 */
public class VistaMenu extends javax.swing.JFrame {
     private Servicios servicios;
    private VistaMenu vistam;

    VistaMusica controladorMusica = new VistaMusica();
    ControladorRaimon raimon = new ControladorRaimon(servicios);
    private ArrayList<Jugador> jugadores;
    private VistaRaimon vistaR = new VistaRaimon(jugadores);

    /**
     * Creates new form Menu
     */
    
    public VistaMenu() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jColorChooser1 = new javax.swing.JColorChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog1 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Otaku = new javax.swing.JButton();
        Occult = new javax.swing.JButton();
        Brain = new javax.swing.JButton();
        Shuriken = new javax.swing.JButton();
        Street_Sallys = new javax.swing.JButton();
        Wild = new javax.swing.JButton();
        Inazuma_KFC = new javax.swing.JButton();
        Umbrella = new javax.swing.JButton();
        RaimonOG = new javax.swing.JButton();
        Raimon = new javax.swing.JButton();
        Farm = new javax.swing.JButton();
        Royal_Academy = new javax.swing.JButton();
        Zeus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo_red_2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));

        Fondo.setBackground(new java.awt.Color(0, 102, 255));

        Otaku.setBackground(new java.awt.Color(255, 102, 0));
        Otaku.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Otaku.setForeground(new java.awt.Color(255, 255, 255));
        Otaku.setText("Otaku");
        Otaku.setToolTipText("");
        Otaku.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Otaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtakuActionPerformed(evt);
            }
        });

        Occult.setBackground(new java.awt.Color(255, 102, 0));
        Occult.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Occult.setForeground(new java.awt.Color(255, 255, 255));
        Occult.setText("Occult");
        Occult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Occult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OccultActionPerformed(evt);
            }
        });

        Brain.setBackground(new java.awt.Color(255, 102, 0));
        Brain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Brain.setForeground(new java.awt.Color(255, 255, 255));
        Brain.setText("Brain");
        Brain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Brain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrainActionPerformed(evt);
            }
        });

        Shuriken.setBackground(new java.awt.Color(255, 102, 0));
        Shuriken.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Shuriken.setForeground(new java.awt.Color(255, 255, 255));
        Shuriken.setText("Shuriiken");
        Shuriken.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Shuriken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShurikenActionPerformed(evt);
            }
        });

        Street_Sallys.setBackground(new java.awt.Color(255, 102, 0));
        Street_Sallys.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Street_Sallys.setForeground(new java.awt.Color(255, 255, 255));
        Street_Sallys.setText("Street Sally`s");
        Street_Sallys.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Street_Sallys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Street_SallysActionPerformed(evt);
            }
        });

        Wild.setBackground(new java.awt.Color(255, 102, 0));
        Wild.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Wild.setForeground(new java.awt.Color(255, 255, 255));
        Wild.setText("Wild");
        Wild.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Wild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WildActionPerformed(evt);
            }
        });

        Inazuma_KFC.setBackground(new java.awt.Color(255, 102, 0));
        Inazuma_KFC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Inazuma_KFC.setForeground(new java.awt.Color(255, 255, 255));
        Inazuma_KFC.setText("Inazuma Kids FC");
        Inazuma_KFC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Inazuma_KFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inazuma_KFCActionPerformed(evt);
            }
        });

        Umbrella.setBackground(new java.awt.Color(255, 102, 0));
        Umbrella.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Umbrella.setForeground(new java.awt.Color(255, 255, 255));
        Umbrella.setText("Umbrella");
        Umbrella.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Umbrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmbrellaActionPerformed(evt);
            }
        });

        RaimonOG.setBackground(new java.awt.Color(255, 102, 0));
        RaimonOG.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RaimonOG.setForeground(new java.awt.Color(255, 255, 255));
        RaimonOG.setText("Raimon OG");
        RaimonOG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RaimonOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaimonOGActionPerformed(evt);
            }
        });

        Raimon.setBackground(new java.awt.Color(255, 102, 0));
        Raimon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Raimon.setForeground(new java.awt.Color(255, 255, 255));
        Raimon.setText("Raimon");
        Raimon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Raimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaimonActionPerformed(evt);
            }
        });

        Farm.setBackground(new java.awt.Color(255, 102, 0));
        Farm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Farm.setForeground(new java.awt.Color(255, 255, 255));
        Farm.setText("Farm");
        Farm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Farm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FarmActionPerformed(evt);
            }
        });

        Royal_Academy.setBackground(new java.awt.Color(255, 102, 0));
        Royal_Academy.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Royal_Academy.setForeground(new java.awt.Color(255, 255, 255));
        Royal_Academy.setText("Royal Academy");
        Royal_Academy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Royal_Academy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Royal_AcademyActionPerformed(evt);
            }
        });

        Zeus.setBackground(new java.awt.Color(255, 102, 0));
        Zeus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Zeus.setForeground(new java.awt.Color(255, 255, 255));
        Zeus.setText("Zeus");
        Zeus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Zeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeusActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo_red_2.png"))); // NOI18N

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Zeus, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RaimonOG, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Street_Sallys, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Brain, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Royal_Academy, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Shuriken, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wild, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Umbrella, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Raimon, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Otaku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Occult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inazuma_KFC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Farm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wild, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Royal_Academy, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Otaku, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Brain, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Shuriken, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Occult, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Street_Sallys, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Umbrella, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inazuma_KFC, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RaimonOG, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Raimon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Farm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(Zeus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Royal_AcademyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Royal_AcademyActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/Jude_Royal.wav");
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_Royal_AcademyActionPerformed

    private void BrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrainActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_BrainActionPerformed

    private void ZeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeusActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");
        controladorMusica.playSound("src/resources_audio/Byron_Zeus.wav");
    }//GEN-LAST:event_ZeusActionPerformed

    private void Street_SallysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Street_SallysActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_Street_SallysActionPerformed

    private void RaimonOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaimonOGActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_RaimonOGActionPerformed

    private void WildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WildActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

        
    }//GEN-LAST:event_WildActionPerformed

    private void ShurikenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShurikenActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_ShurikenActionPerformed

    private void UmbrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmbrellaActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_UmbrellaActionPerformed

    private void RaimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaimonActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");
        raimon.cargarJugadores();
        vistaR.setLocationRelativeTo(null);
        ArrayList<Jugador> jugadores = new ControladorRaimon(servicios).cargarJugadores();
        new VistaRaimon(jugadores);
        
        vistaR.setTitle("Raimon");
        

    }//GEN-LAST:event_RaimonActionPerformed

    private void OtakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtakuActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_OtakuActionPerformed

    private void OccultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OccultActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_OccultActionPerformed

    private void Inazuma_KFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inazuma_KFCActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_Inazuma_KFCActionPerformed

    public JButton getRaimon() {
        return Raimon;
    }

    public void setRaimon(JButton Raimon) {
        this.Raimon = Raimon;
    }

    private void FarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FarmActionPerformed
        // TODO add your handling code here:
        controladorMusica.playSound("src/resources_audio/OK.wav");

    }//GEN-LAST:event_FarmActionPerformed

    
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Brain;
    private javax.swing.JButton Farm;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Inazuma_KFC;
    private javax.swing.JButton Occult;
    private javax.swing.JButton Otaku;
    private javax.swing.JButton Raimon;
    private javax.swing.JButton RaimonOG;
    private javax.swing.JButton Royal_Academy;
    private javax.swing.JButton Shuriken;
    private javax.swing.JButton Street_Sallys;
    private javax.swing.JButton Umbrella;
    private javax.swing.JButton Wild;
    private javax.swing.JButton Zeus;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
